Celmedia\PillsBundle\Entity\Client:
    type: entity
    table: user_client
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
                
       
    lifecycleCallbacks: {  }
