Celmedia\PillsBundle\Entity\Pill:
    type: entity
    table: pill
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        descripcion:
            type: string
            length: 140
            fixed: false
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
        imagen:
            type: text
            nullable: true
        fechacreacion:
            type: datetime
            nullable: false
            column: fechaCreacion
            
            
    manyToMany:
      tags:
        targetEntity: Tag
        cascade: ["persist", "merge"]
        joinTable:
          name: pill_tags
          joinColumns:
            pill_id:
              referencedColumnName: id
          inverseJoinColumns:
            tag_id:
              referencedColumnName: id
      categorias:
        targetEntity: Categoria
        joinTable:
          name: pill_categorias
          joinColumns:
            pill_id:
              referencedColumnName: id
          inverseJoinColumns:
            categorias_id:
              referencedColumnName: id
        
        
    manyToOne:
        usuario:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario:
                    referencedColumnName: id
            orphanRemoval: false
            cascade: ["persist", "merge"]
        estudio:
            targetEntity: Estudio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                estudio:
                    referencedColumnName: id
            orphanRemoval: false
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
