Celmedia\PillsBundle\Entity\Tipocalificacion:
    type: entity
    table: tipocalificacion
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        descripcion:
            type: string
            length: 250
            fixed: false
            nullable: false
        estado:
            type: integer
            unsigned: false
            nullable: false
    lifecycleCallbacks: {  }
